spring.application.name=ElGuPoServer
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:8080/ElGuPoServer
spring.datasource.username=root
spring.datasource.password=ElGuPo
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath*:database/initDB.sql