CREATE TABLE IF NOT EXISTS users
(
    id    BIGSERIAL PRIMARY KEY ,
    name  VARCHAR(200) NOT NULL ,
    surname  VARCHAR(200) NOT NULL ,
    age INT8 NOT NULL ,
    email VARCHAR(254) NOT NULL ,
    password VARCHAR(254) NOT NULL
);